---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: "{{ .Values.global.services_namespace }}"
  labels:
    app-name: minio
spec:
  selector:
    app-name: minio
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
---